version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: restaurant-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 27102005Az
      MYSQL_DATABASE: Restaurant_Manager
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./restaurant-be/Restaurant_Manager
    container_name: restaurant-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./restaurant-fe
    container_name: restaurant-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data: