spring:
  application:
    name: Restaurant_Manager
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/Restaurant_Manager
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

signer_key: ${SIGNER_KEY}

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE